### ISSUE TITLE
Typo in project name

### ISSUE THREAD

**Issue by SIMULATAN** [Stenz123/hearbeat-jumpscare#1]
who's a "hearbeat" @Stenz123 ???

**Comment by Stenz123** [comment]
fixed

**Comment by SIMULATAN** [comment]
Great!
![image](https://github.com/user-attachments/assets/30dd7142-cb3f-4a67-b281-b97abf0a899b)

**Comment by SIMULATAN** [comment]
Thank you!

**Comment by SIMULATAN** [comment]
Awesome to see!

**Comment by SIMULATAN** [comment]
Best of luck!

**Comment by Stenz123** [comment]
nice of you to mention is unforgivable issue
